# Generated by Django 4.2.4 on 2025-05-13 15:37

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimateNews",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("article_url", models.TextField(default="Some String")),
                ("title", models.TextField(default="Some String")),
                ("author", models.TextField(default="Some String")),
                ("type", models.TextField(default="Some String")),
                ("category", models.TextField(default="Some String")),
                ("subcategory", models.TextField(default="Some String")),
                ("text", models.TextField(default="Some String")),
                ("date", models.TextField(default="Some String")),
                ("time", models.TextField(default="Some String")),
                ("image_url", models.TextField(default="Some String")),
                ("image_caption", models.TextField(default="Some String")),
                ("author_bio", models.TextField(default="Some String")),
                ("subtype", models.TextField(default="Some String")),
            ],
            options={
                "verbose_name": "ClimateNews",
                "db_table": "ClimateNews",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="NewsRec",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "article_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("title", models.CharField(default="Some String", max_length=500)),
                ("category", models.CharField(blank=True, default="", max_length=50)),
                ("text", models.TextField(default="Some String")),
                (
                    "image",
                    models.ImageField(blank=True, default="", upload_to="images/UMAP/"),
                ),
                ("summary_neutral", models.TextField(blank=True, default="")),
                ("summary_fearful", models.TextField(blank=True, default="")),
                ("summary_fear_hope", models.TextField(blank=True, default="")),
                ("fetched_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NewsRec",
                "db_table": "NewsRec",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Personal_info",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="Personal_info", editable=False, max_length=50
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            (None, ""),
                            ("under_18", "Under 18"),
                            ("b18_24", "18-24"),
                            ("b25_35", "25-35"),
                            ("b35_45", "35-45"),
                            ("b45_55", "45-55"),
                            ("over_55", "Over 55"),
                        ],
                        default=None,
                        max_length=120,
                        verbose_name="age",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "education",
                    models.CharField(
                        choices=[
                            (None, ""),
                            ("Less_high_school", "Less than high school"),
                            ("High_school", "High school or equivalent"),
                            ("BA", "Bachelor degree (e.g. BA, BSc)"),
                            ("MSc", "Master degree (e.g. MA, MSc)"),
                            ("Doctorate", "Doctorate (e.g. PhD)"),
                            ("Not", "Prefer not to say"),
                        ],
                        default=None,
                        max_length=120,
                        verbose_name="education",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("refuse_to_disc", "Other / Prefer not to say"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="gender",
                    ),
                ),
                (
                    "prolific_username",
                    models.CharField(
                        default=None,
                        max_length=100,
                        unique=True,
                        verbose_name="prolific ID",
                    ),
                ),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "clicked_articles_list",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                ("clicked_articles_details", models.JSONField(default=list)),
                ("phase_one_complete", models.BooleanField(default=False)),
                ("phase_two_complete", models.BooleanField(default=False)),
                ("phase_three_complete", models.BooleanField(default=False)),
                (
                    "redemption_code_phase1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "redemption_code_phase2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "redemption_code_phase3",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "personal_info",
                "db_table": "personal_info",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Ghs_fk2",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ghs_fk2",
                        serialize=False,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(default="Ghs_fk2", editable=False, max_length=50),
                ),
                (
                    "iterations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {FK_1, FK_2, FK_3, FK_4, timestamp} dicts",
                    ),
                ),
            ],
            options={
                "db_table": "ghs_fk2",
            },
        ),
        migrations.CreateModel(
            name="Topic_preference",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="topic_preference", editable=False, max_length=50
                    ),
                ),
                (
                    "politikk",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Politikk",
                    ),
                ),
                (
                    "okonomi_og_naeringsliv",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Økonomi og næringsliv",
                    ),
                ),
                (
                    "kriminalitet_og_rettssaker",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Kriminalitet og rettssaker",
                    ),
                ),
                (
                    "utenriks_og_globale_konflikter",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Utenriks og globale konflikter",
                    ),
                ),
                (
                    "samfunn_og_arbeidsliv",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Samfunn og arbeidsliv",
                    ),
                ),
                (
                    "klima_og_miljo",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Klima og miljø",
                    ),
                ),
                (
                    "helse_og_forskning",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Helse og forskning",
                    ),
                ),
                (
                    "teknologi_og_vitenskap",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Teknologi og vitenskap",
                    ),
                ),
                (
                    "sport",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Sport",
                    ),
                ),
                (
                    "underholdning_og_kjendiser",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Underholdning og kjendiser",
                    ),
                ),
                (
                    "livsstil_og_helse",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Livsstil og helse",
                    ),
                ),
                (
                    "mat_og_drikke",
                    models.IntegerField(
                        choices=[(-1, "Dislike"), (0, "Neutral"), (1, "Like")],
                        default=0,
                        verbose_name="Mat og drikke",
                    ),
                ),
                (
                    "media_usage",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("rarely", "Rarely"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "media_access",
                    models.CharField(
                        help_text="Velg alle som gjelder (kommaseparert)",
                        max_length=200,
                    ),
                ),
                (
                    "news_source",
                    models.CharField(
                        help_text="Velg alle som gjelder (kommaseparert)",
                        max_length=200,
                    ),
                ),
                ("session_id", models.CharField(default="", max_length=100, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "topic_preference",
                "db_table": "topic_preference",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Recommendations",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("recommended_recipes", models.CharField(max_length=500)),
                ("healthiness", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "recommendations",
                "db_table": "Recommendations",
            },
        ),
        migrations.CreateModel(
            name="Ghs_fk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="Knowledge health", editable=False, max_length=50
                    ),
                ),
                (
                    "FK_1",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_1",
                    ),
                ),
                (
                    "FK_2",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_2",
                    ),
                ),
                (
                    "FK_3",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_3",
                    ),
                ),
                (
                    "FK_4",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_4",
                    ),
                ),
                (
                    "FK_5",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_5",
                    ),
                ),
                (
                    "FK_6",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_6",
                    ),
                ),
                (
                    "FK_7",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_7",
                    ),
                ),
                (
                    "FK_8",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_8",
                    ),
                ),
                (
                    "FK_9",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_9",
                    ),
                ),
                (
                    "FK_10",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=300,
                        verbose_name="FK_10",
                    ),
                ),
                ("session_id", models.CharField(default="", max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ghs_fk",
                "db_table": "ghs_fk",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices9",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices9", editable=False, max_length=50
                    ),
                ),
                (
                    "liked_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="liked_news9",
                    ),
                ),
                (
                    "trust_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="trust_news9",
                    ),
                ),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="fit_preference9",
                    ),
                ),
                (
                    "recommend_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="recommend_news9",
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices9",
                "db_table": "EvaluateChoices9",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices8",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices8", editable=False, max_length=50
                    ),
                ),
                (
                    "liked_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="liked_news8",
                    ),
                ),
                (
                    "trust_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="trust_news8",
                    ),
                ),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="fit_preference8",
                    ),
                ),
                (
                    "recommend_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="recommend_news8",
                    ),
                ),
                (
                    "many_to_choose",
                    models.CharField(
                        choices=[
                            ("Red", "Red"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                            ("Orange", "Orange"),
                            ("Brown", "Brown"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="many_to_choose",
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices8",
                "db_table": "EvaluateChoices8",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices7",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices7", editable=False, max_length=50
                    ),
                ),
                (
                    "liked_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="liked_news7",
                    ),
                ),
                (
                    "trust_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="trust_news7",
                    ),
                ),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="fit_preference7",
                    ),
                ),
                (
                    "recommend_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="recommend_news7",
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices7",
                "db_table": "EvaluateChoices7",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices6",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices6", editable=False, max_length=50
                    ),
                ),
                (
                    "liked_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="liked_news6",
                    ),
                ),
                (
                    "trust_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="trust_news6",
                    ),
                ),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="fit_preference6",
                    ),
                ),
                (
                    "recommend_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="recommend_news6",
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices6",
                "db_table": "EvaluateChoices6",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices5",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices5", editable=False, max_length=50
                    ),
                ),
                (
                    "liked_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="liked_news5",
                    ),
                ),
                (
                    "trust_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="trust_news5",
                    ),
                ),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="fit_preference5",
                    ),
                ),
                (
                    "recommend_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="recommend_news5",
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices5",
                "db_table": "EvaluateChoices5",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices4",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices4", editable=False, max_length=50
                    ),
                ),
                (
                    "liked_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="liked_news4",
                    ),
                ),
                (
                    "trust_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="trust_news4",
                    ),
                ),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="fit_preference4",
                    ),
                ),
                (
                    "recommend_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="recommend_news4",
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices4",
                "db_table": "EvaluateChoices4",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices3",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices3", editable=False, max_length=50
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices3",
                "db_table": "EvaluateChoices3",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices2",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices2", editable=False, max_length=50
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices2",
                "db_table": "EvaluateChoices2",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices10",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices10", editable=False, max_length=50
                    ),
                ),
                (
                    "liked_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="liked_news10",
                    ),
                ),
                (
                    "trust_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="trust_news10",
                    ),
                ),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="fit_preference10",
                    ),
                ),
                (
                    "recommend_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="recommend_news10",
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices10",
                "db_table": "EvaluateChoices10",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluateChoices",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        default="EvaluateChoices", editable=False, max_length=50
                    ),
                ),
                (
                    "read_more",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="read_more",
                    ),
                ),
                (
                    "liked_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="liked_news",
                    ),
                ),
                (
                    "trust_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="trust_news",
                    ),
                ),
                (
                    "fit_preference",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="fit_preference",
                    ),
                ),
                (
                    "mood_fit",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="mood_fit",
                    ),
                ),
                (
                    "recommend_news",
                    models.CharField(
                        choices=[
                            ("Strongly_Disagree", "1 - Strongly Disagree"),
                            ("Disagree", "2"),
                            ("Neutral", "3"),
                            ("Agree", "4"),
                            ("Strongly_Agree", "5 - Strongly Agree"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="recommend_news",
                    ),
                ),
                (
                    "many_to_choose",
                    models.CharField(
                        choices=[
                            ("Red", "Red"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                            ("Orange", "Orange"),
                            ("Brown", "Brown"),
                        ],
                        default=None,
                        max_length=100,
                        verbose_name="many_to_choose",
                    ),
                ),
                ("created", models.CharField(default="0", max_length=1000)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "EvaluateChoices",
                "db_table": "EvaluateChoices",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SelectedRecipe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("recipe_id", models.IntegerField()),
                ("recipe_name", models.CharField(max_length=200)),
                ("Nutri_score", models.CharField(max_length=100)),
                ("fsa_score", models.CharField(max_length=100)),
                ("healthiness", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(default=None, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "selectedRecipe",
                "db_table": "selectedrecipe",
                "unique_together": {("person", "recipe_id")},
            },
        ),
        migrations.CreateModel(
            name="ArticleClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase", models.PositiveSmallIntegerField()),
                ("session_id", models.CharField(max_length=40, null=True)),
                (
                    "article_ids",
                    models.JSONField(
                        default=list, help_text="List of all clicked article IDs"
                    ),
                ),
                (
                    "cluster_ids",
                    models.JSONField(
                        default=list, help_text="List of matching cluster IDs"
                    ),
                ),
                (
                    "titles",
                    models.JSONField(
                        default=list, help_text="List of all article titles"
                    ),
                ),
                (
                    "sources",
                    models.JSONField(default=list, help_text="List of all sources"),
                ),
                (
                    "topics",
                    models.JSONField(
                        default=list, help_text="List of API‐returned topics"
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labels_Nudges.personal_info",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="Labels_Nudg_session_f006da_idx"
                    )
                ],
            },
        ),
    ]
