# Generated by Django 4.2.4 on 2025-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal_info",
            name="clicked_articles_list",
            field=models.JSONField(default=list),
        ),
    ]
