# Generated by Django 4.2.4 on 2025-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0003_personal_info_phase1_elapsed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleclick",
            name="phase1_elapsed",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Seconds spent in Phase 1 before submit",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="articleclick",
            name="phase1_start",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when Phase 1 began", null=True
            ),
        ),
    ]
