# Generated by Django 4.2.4 on 2025-05-28 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0004_articleclick_phase1_elapsed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personal_info",
            name="phase_three_complete",
        ),
        migrations.RemoveField(
            model_name="personal_info",
            name="redemption_code_phase3",
        ),
    ]
