# Generated by Django 4.2.4 on 2025-05-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0005_remove_personal_info_phase_three_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleclick",
            name="click_data",
            field=models.JSONField(
                default=list,
                help_text='List of {"id": str, "title": str, "similarity": float, "cluster": str, "explore": bool, "source": str, "topics": [str], "clicked_at": str}',
            ),
        ),
        migrations.AlterField(
            model_name="articleclick",
            name="clicked_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the user submitted their clicks"
            ),
        ),
        migrations.AlterField(
            model_name="articleclick",
            name="phase",
            field=models.PositiveSmallIntegerField(
                help_text="Which phase these clicks belong to"
            ),
        ),
        migrations.AlterField(
            model_name="articleclick",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Django session_key", max_length=40, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articleclick",
            unique_together={("person", "phase")},
        ),
        migrations.RemoveField(
            model_name="articleclick",
            name="article_ids",
        ),
        migrations.RemoveField(
            model_name="articleclick",
            name="cluster_ids",
        ),
        migrations.RemoveField(
            model_name="articleclick",
            name="sources",
        ),
        migrations.RemoveField(
            model_name="articleclick",
            name="titles",
        ),
        migrations.RemoveField(
            model_name="articleclick",
            name="topics",
        ),
    ]
