# Generated by Django 4.2.4 on 2025-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0006_articleclick_click_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleclick",
            name="phase2_elapsed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articleclick",
            name="phase2_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
