# Generated by Django 4.2.4 on 2025-06-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0007_articleclick_phase2_elapsed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleclick",
            name="percent_familiar",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articleclick",
            name="total_clicked",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
