# Generated by Django 4.2.4 on 2025-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0008_articleclick_percent_familiar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ghs_fk2",
            name="iterations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of response dictionaries per iteration, each containing: like_chosen, looking_forward, fit_preferences, know_better, interesting, fitted_preferences, relevant, similar_to_each_other, differed_topics, diversity_high, and timestamp.",
            ),
        ),
    ]
