# Generated by Django 4.2.4 on 2025-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0009_alter_ghs_fk2_iterations"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic_preference",
            name="history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {'timestamp': ISO8601 string, 'preferences': {field_name: value, …}}",
            ),
        ),
    ]
