# Generated by Django 4.2.4 on 2025-06-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labels_Nudges", "0010_topic_preference_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal_info",
            name="last_home",
            field=models.DateTimeField(
                blank=True,
                help_text="When the participant last visited home",
                null=True,
            ),
        ),
    ]
